[project]
name = "digital-earth-hackathon"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "numpy>=2.4.6",
    "openeo>=0.50.0",
    "pandas>=2.3.3",
    "rich>=15.0.0",
    "streamlit>=1.40.0",
    "geopandas>=1.0.0",
    "shapely>=2.0.0",
    "xarray>=2025.0.0",
    "rioxarray>=0.20.0",
    "rasterio>=1.4.0",
    "h5netcdf>=1.8.1",
    "plotly>=6.0.0",
    "pydeck>=0.9.0",
    "folium>=0.19.0",
    "h5py>=3.16.0",
    "netcdf4>=1.7.4",
    "owslib>=0.36.0",
    "openpyxl>=3.1.5",
    "matplotlib>=3.10.9",
    "pcse>=5.6.2",
    "requests>=2.31.0",
]
